#!/bin/bash
echo "=== Testing Backend Filters ==="
echo ""
echo "1. No filters:"
curl -s "http://localhost:3001/api/sales" | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'   Total: {d[\"pagination\"][\"totalItems\"]}')"
echo ""
echo "2. Region filter (East):"
curl -s "http://localhost:3001/api/sales?regions=East" | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'   Total: {d[\"pagination\"][\"totalItems\"]}')"
echo ""
echo "3. Gender filter (Male):"
curl -s "http://localhost:3001/api/sales?genders=Male" | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'   Total: {d[\"pagination\"][\"totalItems\"]}')"
echo ""
echo "4. Category filter (Electronics):"
curl -s "http://localhost:3001/api/sales?categories=Electronics" | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'   Total: {d[\"pagination\"][\"totalItems\"]}')"
echo ""
echo "5. Multiple filters (East + Male):"
curl -s "http://localhost:3001/api/sales?regions=East&genders=Male" | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'   Total: {d[\"pagination\"][\"totalItems\"]}')"
echo ""
echo "=== Backend Tests Complete ==="
